version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'oddesign'
      POSTGRES_PASSWORD: 'qwerasdf'
    volumes:
      - './docker_data/postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass yourpassword
    ports:
      - '6380:6379'
    volumes:
      - './docker_data/redis:/var/lib/redis/data'
